---
name: CodeProject AI.Server (CPU)
version: 2.9.7
url: https://hub.docker.com/r/codeproject/ai-server
image: "ghcr.io/stevusprimus/hassio-addon-ai.server-{arch}"
panel_icon: mdi:face-recognition
slug: codeprojectai
description: standalone open-source AI server
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 32168
ingress_stream: true
startup: services
boot: auto
init: false
full_access: false
usb: true
video: true
ingress: false
privileged:
  - PERFMON
ports:
  32168/tcp: 32168
  32168/udp: 32168
  5000/tcp: 5000
map:
  - config:rw
environment:
  HA_ADDON: "true"
  DATA_DIR: "/config/ai-server/data"
  MODULES_PATH: "/config/ai-server/modules"
options:
  MODULES_PATH: "/config/ai-server/modules"
  DATA_DIR: "/config/ai-server/data"
schema:
  MODULES_PATH: str
  DATA_DIR: str

