---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Codeproject.Ai"
  #org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/StevusPrimus/skarashevich-hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"